### ISSUE TITLE
Firefox problems with mouse events

### ISSUE THREAD

**Issue by NCrashed** [bergey/gooey#1]
Hi, the `diagrams-reflex-counting` and `diagrams-reflex-follow` seem to not respond to mouse input at all. 

The chrome works pretty well. 

Platform: Fedora 24 x86_64
Firefox: 47.0.1

**Comment by NCrashed** [comment]
I built the `diagrams-reflex-follow` example by myself (variant with arrow) and it works with Firefox, although very laggy in contrast with Chrome.

**Comment by bergey** [comment]
Thanks for reporting this!  I also see that they don't work in Firefox.

I've given you access to the repository.  If you can push the working build to the `gh-pages` branch, that would be great.

In my experience, Firefox is slower than Chrome at SVG even when Haskell is not involved (eg, d3.js).  I'd welcome patches (probably to https://github.com/diagrams/diagrams-reflex) that improve this.  I'm afraid I won't have time to work on it myself for six months or more.

**Comment by NCrashed** [comment]
Pushed! 

Also I used `lts-6.6` to build them, should I push updated `stack.yaml` in master branch?

**Comment by bergey** [comment]
Thanks!  Yes, please update the `stack.yaml`.

**Comment by NCrashed** [comment]
Done with 774795ab95058f66b57f1004a0fcc1d541176771, the issue resolved! Thank you!
